### ISSUE TITLE
Some clarification

### ISSUE THREAD

**Issue by sanihaq** [nank1ro/solidart#13]
HI, thanks for this amazing package. I have some question regarding disposing of a signal.

When using this way -
```dart
Solid(
      providers: [
        SolidProvider<FilesController>(
          create: () => FilesController(),
          dispose: (controller) => controller.dispose(), // does dispose gets automatically called, I dont have to dispose else where?
        ),
      ],
...
}
```
or
```dart
Solid(
      signals: {MySignals.someSignal: () => createSignal<bool>(false)}, // I have to dispose, when I dont need it any more?
...
)
```

Hope I manage to explain it properly. Thanks.

**Comment by nank1ro** [comment]
Hi, thank you for choosing solidart 💪

When using the Solid widget, the life cycle of signals and providers is automatically managed by Solid.
This means that when the Solid widget is removed from the tree, all associated signals and providers are automatically disposed.
You don't have to dispose them yourself, Solid knows the exact moment when you no longer need signals and providers.

For providers, there is the `dispose` method to be added manually as you decide what to do, since I do not know the shape of the class. In other words, I do not know whether your class contains a method called `dispose`.
This means that you can also call a method called `controller.cleanup()` or whatever you need.

**Comment by sanihaq** [comment]
@nank1ro so I don't have to think about cleanup at all. Except when I'm creating my own provider, in that case I have to create a “dispose” (or similar name method) and handle all the signal inside that provider and pass that to the initial Solid widget. Is that it?

**Comment by nank1ro** [comment]
Yes, to recap:
```dart
Solid(
      signals: {MySignals.someSignal: () => createSignal<bool>(false)},
...
)
```
☝🏼 signals created inside the `Solid` widget automatically dispose

```dart
SolidProvider<FilesController>(
          create: () => FilesController(),
          dispose: (controller) => controller.dispose(),
        ),
```
☝🏼 providers created inside the `Solid` widget will call the `dispose` method you provide
In your FilesController `dispose` method you have to dispose all the `signals` or `resources` you have created inside.

Thank you for your suggestions! I'm surely going to add a testing chapter to the documentation. 
What else do you think needs to be explained more in details?

**Comment by sanihaq** [comment]
@nank1ro ok, got it. 💡👌
As I said, simplicity is really a plus point for this package. There are a lot of simple to get state management available out there (e.g. riverpod). But are not seems so easy at first glance (and that's a pretty negative point from my point of view).
So, keep the simplicity (in the docs and in the package).
That being said, I wouldn't mind further resource to get more performance out of this package. Like, do I have to use a stateful widget everywhere to get a provider. As a general rule, we should have less not more stateful widget.

Thank you. I hope this get much more wide adoption in the future. Good luck.🤞

**Comment by sanihaq** [comment]
@nank1ro yes it makes sense of what you said, perhaps I came to the wrong conclusion seeing it in some example and not thinking of other possibilities. My bad.
